[default]
locale = "en-us"

[files]
extend-exclude = [
    # generated files
    "book/ethicalads-theme.css",
    "fuzzing/fuzz/artifacts/",
    "fuzzing/fuzz/corpus/",
    "target/",
    "rinja_parser/tests/*.txt",
    "testing/templates/fuzzed-*",
    # filler texts
    "rinja/benches/strings.inc",
    # too many false positives
    "testing/tests/gen_ws_tests.py",
]

[default.extend-words]
# It's actually called that in the ASCII standard
Enquiry = "Enquiry"

# French words
exemple = "exemple"
existant = "existant"

# used in tests
Ba = "Ba"
fo = "fo"
Fo = "Fo"
sur = "sur"
